name-template: v$RESOLVED_VERSION
tag-template: v$RESOLVED_VERSION
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'

categories:
  - title: Features
    labels: [feat]
  - title: Bug Fixes
    labels: [fix]
  - title: Breaking Changes
    labels: [breaking]
  - title: Maintenance
    labels: [chore]

template: |
  ## Changes

  $CHANGES
