// Copyright © 2026 Kaleido, Inc.
//
// SPDX-License-Identifier: Apache-2.0

package io.kaleido.workflowengine.sdk.errors;

/**
 * SDK error message catalog, in two ranges.
 *
 * <p><strong>KA1406XX is shared across the Kaleido SDK family.</strong> A code
 * means the same thing in every language SDK, so a code is never repurposed to
 * say something new, and a new one is only allocated in step with the others.
 * The whole of KA1406XX is reserved for that shared set. Gaps are
 * codes another SDK claimed for a condition this one does not have.
 *
 * <p><strong>KA1500XX is this SDK's own.</strong> Conditions with no counterpart
 * elsewhere are allocated here, leaving the shared range free to grow without
 * colliding.
 *
 * <p>Within each range codes are allocated in creation order, so the groupings
 * below are for reading and do not own contiguous blocks.
 */
public final class SDKErrors {
    private SDKErrors() {}

    public record ErrorMessage(String code, String message) {}

    private static ErrorMessage fe(String code, String template) {
        return new ErrorMessage(code, template);
    }

    // Handler errors (KA1406XX)
    public static final ErrorMessage MSG_OBSERVED_PANIC = fe("KA140600", "Observed panic: %s");
    public static final ErrorMessage MSG_UNKNOWN_HANDLER = fe("KA140601", "Unknown handler '%s'");
    public static final ErrorMessage MSG_NO_LISTENER_CONFIG = fe("KA140602", "Listener config for stream '%s' not supplied by workflow engine");
    public static final ErrorMessage MSG_OUTPUT_SERIALIZATION_ERROR = fe("KA140603", "Unable to serialize output to %s");
    public static final ErrorMessage MSG_DIRECTOR_NEXT_STAGE_MISSING = fe("KA140604", "Handler called with 'nextStage' missing from input");
    public static final ErrorMessage MSG_DIRECTOR_OUTPUT_PATH_MISSING = fe("KA140605", "Handler called with 'outputPath' missing from input");
    public static final ErrorMessage MSG_DIRECTOR_FAILURE_STAGE_MISSING = fe("KA140606", "Handler resulted in a failure, but 'failureStage' missing from input");
    public static final ErrorMessage MSG_INPUT_PARSING_ERROR = fe("KA140607", "Unable to parse input");
    public static final ErrorMessage MSG_INVALID_ACTION = fe("KA140608", "Action '%s' is invalid for handler '%s'");
    public static final ErrorMessage MSG_INVALID_RESULT = fe("KA140609", "Action '%s' gave unexpected result '%s' without error");

    // Event source errors
    public static final ErrorMessage MSG_CHECKPOINT_INVALID_FOR_HANDLER = fe("KA140610", "Checkpoint could not be parsed by handler '%s'");
    public static final ErrorMessage MSG_STREAM_CONFIG_INVALID_FOR_HANDLER = fe("KA140611", "Event stream config could not be parsed by handler '%s'");
    public static final ErrorMessage MSG_CHECKPOINT_INVALID = fe("KA140612", "Checkpoint generated by handler '%s' cannot be serialized");
    public static final ErrorMessage MSG_EVENT_SOURCE_DATA_INVALID = fe("KA140613", "Event source data could not be serialized for handler '%s'");

    // Engine API errors
    public static final ErrorMessage MSG_ENGINE_REPLY_INVALID_DATA = fe("KA140614", "Engine API reply for transaction %s invalid: %s");
    public static final ErrorMessage MSG_ENGINE_REPLY_INVALID_TYPE = fe("KA140615", "Engine API reply type for transaction %s invalid: %s");
    public static final ErrorMessage MSG_ENGINE_FAIL_MARSHAL_REQUEST = fe("KA140617", "Failed to marshal engine transaction data");
    public static final ErrorMessage MSG_ENGINE_FAIL_SEND_REQUEST = fe("KA140618", "Failed to send engine transaction");

    // Configuration errors
    public static final ErrorMessage MSG_PROVIDER_NAME_NOT_SET = fe("KA140620", "Provider name not set");
    public static final ErrorMessage MSG_URL_REQUIRED_OUTBOUND = fe("KA140630", "URL is required in outbound mode");
    public static final ErrorMessage MSG_ACCOUNT_NOT_SET = fe("KA140632", "ACCOUNT is not set and no baseUrl provided");
    public static final ErrorMessage MSG_ENVIRONMENT_NOT_SET = fe("KA140633", "ENVIRONMENT is not set and no baseUrl provided");
    public static final ErrorMessage MSG_WORKFLOW_ENGINE_NOT_SET = fe("KA140634", "WORKFLOW_ENGINE is not set and no baseUrl provided");

    // Stage Director errors
    public static final ErrorMessage MSG_HANDLER_NOT_CONFIGURED = fe("KA140621", "Handler not configured for this action");
    public static final ErrorMessage MSG_BATCH_HANDLER_NOT_CONFIGURED = fe("KA140622", "Handler not configured for BATCH invocation mode");
    public static final ErrorMessage MSG_BATCH_HANDLER_RESULT_COUNT_MISMATCH = fe("KA140623", "Batch handler returned %s results but expected %s");
    public static final ErrorMessage MSG_INPUT_NULL_OR_UNDEFINED = fe("KA140628", "Input is null or undefined in stage %s");
    public static final ErrorMessage MSG_MISSING_ACTION_FIELD = fe("KA140629", "Input is missing required \"action\" field in stage %s. Available fields: %s");

    // Configuration validation errors
    public static final ErrorMessage MSG_CONFIG_UNKNOWN_AUTH_TYPE = fe("KA140626", "Unknown auth type: %s");
    public static final ErrorMessage MSG_CONFIG_FILE_NOT_SET = fe("KA140635", "Workflow engine config file not set: pass a config file or set %s");
    public static final ErrorMessage MSG_CONFIG_FILE_INVALID = fe("KA140636", "Invalid workflow engine config file: %s");
    public static final ErrorMessage MSG_CONFIG_SECTION_MISSING = fe("KA140637", "Missing \"workflow-engine\" section in %s");
    public static final ErrorMessage MSG_HANDLER_INVALID_TYPE = fe("KA140639", "Handler \"%s\" does not implement TransactionHandler, EventSource, or EventProcessor");
    public static final ErrorMessage MSG_DEADLINE_NOT_WAITING = fe("KA140640", "Deadline can only be used with WAITING result type (action='%s' result='%s')");

    // Engine connection errors
    public static final ErrorMessage MSG_ENGINE_NOT_CONNECTED = fe("KA140627", "WebSocket is not connected. Cannot submit async transactions");

    // Errors specific to this SDK (KA1500XX) — see the range note on the class.
    public static final ErrorMessage MSG_REST_REQUEST_FAILED = fe("KA150040", "REST request failed: %s");
    public static final ErrorMessage MSG_REQUEST_CANCELLED = fe("KA150041", "Request cancelled: %s");
    public static final ErrorMessage MSG_SERVICE_BINDING_NOT_FOUND = fe("KA150042", "Service binding '%s' not found. Available bindings: %s");
    public static final ErrorMessage MSG_HANDLER_ALREADY_REGISTERED = fe("KA150043", "Handler '%s' is already registered");
    public static final ErrorMessage MSG_CONFIG_NO_CREDENTIALS = fe("KA150044", "Outbound workflow-engine connection in %s has no credentials: set either tls.certFile for mutual TLS, or auth");
    public static final ErrorMessage MSG_CONFIG_WS_URL_MISSING = fe("KA150045", "Missing ws.url (or a server section) in workflow-engine section in %s");

    /**
     * Format an error message with arguments — supports simple %s placeholders.
     */
    public static String format(ErrorMessage errorMsg, Object... args) {
        var formatted = errorMsg.message();
        for (var arg : args) {
            formatted = formatted.replaceFirst("%s", java.util.regex.Matcher.quoteReplacement(String.valueOf(arg)));
        }
        return errorMsg.code() + ": " + formatted;
    }

    /**
     * Create a new SDKException with an i18n message.
     */
    public static SDKException newError(ErrorMessage errorMsg, Object... args) {
        return new SDKException(errorMsg.code(), format(errorMsg, args));
    }

    /**
     * Create a new SDKException with an i18n message and cause.
     */
    public static SDKException newError(Throwable cause, ErrorMessage errorMsg, Object... args) {
        return new SDKException(errorMsg.code(), format(errorMsg, args), cause);
    }
}
